<?php

/**
 * @file
 * Main hooks for Islandora Compound Everywhere.
 */

/**
 * Implements hook_menu().
 */
function islandora_compound_everywhere_menu() {
  return array(
    'admin/islandora/tools/compound_everywhere' => array(
      'title' => 'Islandora Compound Everywhere',
      'description' => 'Configure Islandora Compound Everywhere.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_compound_everywhere_admin_form'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'includes/admin.form.inc',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function islandora_compound_everywhere_block_info() {
  return array(
    'islandora_compound_e_block' => array(
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => 'islandora/object/*',
      'cache' => DRUPAL_CACHE_PER_PAGE,
      'info' => t('Islandora Compound Everywhere Block'),
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function islandora_compound_everywhere_block_view($delta) {
  module_load_include('inc', 'islandora_compound_everywhere', 'includes/utilities');
  $block = array();
  if ($delta == 'islandora_compound_e_block') {
    $object = menu_get_object('islandora_object', 2);
    if ($object) {
      if (islandora_compound_everywhere_show_for_cmodel($object)) {
        module_load_include('inc', 'islandora_compound_everywhere', 'includes/blocks');
        $block['subject'] = NULL;
        $block['content'] = islandora_compound_everywhere_navigation_block($object);
      }
    }
  }
  return $block;
}

/**
 * Implements hook_islandora_compound_object_children_added_to_parent().
 */
function islandora_compound_everywhere_islandora_compound_object_children_added_to_parent($objects, $parent_pids) {
  // By default, the parent will get the TN of its first child. We don't
  // want that, so we regenerate the parent's TN.
  module_load_include('inc', 'islandora', 'includes/derivatives');
  $options = array('force' => TRUE, 'destination_dsid' => 'TN');
  $object = islandora_object_load($parent_pids[0]);
  islandora_do_derivatives($object, $options);

  // Remove the collection membership of the added children.
  module_load_include('inc', 'islandora', 'includes/utilities');
  foreach ($objects as $child_object) {
    // There should only be one collection but it is possible
    // there are multiple.
    $collections = islandora_get_parents_from_rels_ext($child_object);
    foreach ($collections as $collection) {
      $child_object->relationships->remove(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', $collection->id);
    }
  }
}

/**
 * Theme function overriding template_preprocess_islandora_compound_prev_next().
 */
function islandora_compound_everywhere_preprocess_islandora_compound_prev_next(array &$variables) {
  drupal_add_js(drupal_get_path('module', 'islandora_compound_object') . '/js/caption_width.js');

  $themed_siblings = array();
  $image_path = drupal_get_path('module', 'islandora');
  $folder_image_path = "$image_path/images/folder.png";

  // If the parent hasModel islandora:compoundCModel,
  // the first child is typically identical to the parent;
  // do not show the parent TN.

  // If the parent does not have hasModel islandora:compoundCModel,
  // the first child and parent are different;
  // show the parent TN.

  $variables['parent_tn'] = NULL;
  $parent_object = islandora_object_load($variables['parent_pid']);
  if ($parent_object && !in_array(ISLANDORA_COMPOUND_OBJECT_CMODEL, $parent_object->models)) {
    if (isset($parent_object['TN']) && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $parent_object['TN'])) {
      $variables['parent_tn'] = 'islandora/object/' . $parent_object->id . '/datastream/TN/view';
    }
    else {
      $variables['parent_tn'] = $folder_image_path;
    }
  }

  // If the parent TN is not set, only show children if there's more than one.
  // If the parent TN is set, show all children even if there's only one.

  if (($variables['child_count'] > 1 && !$variables['parent_tn']) || ($variables['child_count'] > 0 && $variables['parent_tn'])) {
  // if (($variables['child_count'] > 0 && !$variables['parent_tn']) || ($variables['child_count'] > 0 && $variables['parent_tn'])) {
    for ($i = 0; $i < count($variables['siblings']); $i += 1) {
      $sibling = array();
      $sibling['pid'] = $variables['siblings'][$i];
      $sibling['class'] = array();
      if ($sibling['pid'] === $variables['pid']) {
        $sibling['class'][] = 'active';
      }
      $sibling_object = islandora_object_load($sibling['pid']);
      if (isset($sibling_object['TN']) && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $sibling_object['TN'])) {
        $sibling['TN'] = 'islandora/object/' . $sibling['pid'] . '/datastream/TN/view';
      }
      else {
        // Object either does not have a thumbnail or it's restricted show a
        // default in its place.
        $sibling['TN'] = $folder_image_path;
      }
      $sibling['label'] = $sibling_object->label;
      $themed_siblings[] = $sibling;
    }
  }
  $variables['themed_siblings'] = $themed_siblings;
}
